// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfy48QrlQmeWCiDj5oRYdsImeiqRhpbEc',
    appId: '1:277293194910:web:2abdc1b6b6cf7779a0658f',
    messagingSenderId: '277293194910',
    projectId: 'tasktodo-5964f',
    authDomain: 'tasktodo-5964f.firebaseapp.com',
    storageBucket: 'tasktodo-5964f.firebasestorage.app',
    measurementId: 'G-7HQ02K3H7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVGarG67MIu4bdnrxjctJIdppVvqeW3_c',
    appId: '1:277293194910:android:d4bd2219fac1cee6a0658f',
    messagingSenderId: '277293194910',
    projectId: 'tasktodo-5964f',
    storageBucket: 'tasktodo-5964f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtxQsLol3iZAJN7ba0YjAbuFFHkw3NLuA',
    appId: '1:277293194910:ios:7ba70cfdfd1c6c31a0658f',
    messagingSenderId: '277293194910',
    projectId: 'tasktodo-5964f',
    storageBucket: 'tasktodo-5964f.firebasestorage.app',
    iosBundleId: 'com.example.tasktodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtxQsLol3iZAJN7ba0YjAbuFFHkw3NLuA',
    appId: '1:277293194910:ios:7ba70cfdfd1c6c31a0658f',
    messagingSenderId: '277293194910',
    projectId: 'tasktodo-5964f',
    storageBucket: 'tasktodo-5964f.firebasestorage.app',
    iosBundleId: 'com.example.tasktodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfy48QrlQmeWCiDj5oRYdsImeiqRhpbEc',
    appId: '1:277293194910:web:24e108349f4c4577a0658f',
    messagingSenderId: '277293194910',
    projectId: 'tasktodo-5964f',
    authDomain: 'tasktodo-5964f.firebaseapp.com',
    storageBucket: 'tasktodo-5964f.firebasestorage.app',
    measurementId: 'G-XF8YBDYZEC',
  );

}